# Generated by Django 3.2.4 on 2021-06-30 12:24

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 2', regex='^.{2}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tag', models.CharField(max_length=60, unique=True)),
                ('description_tag', models.TextField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='banners')),
                ('published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('category', models.ForeignKey(on_delete=models.SET(blog.models.get_other_category), to='blog.category')),
                ('lang', models.ForeignKey(blank=True, on_delete=models.SET(blog.models.get_default_language), to='blog.language')),
                ('liked', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.meta')),
            ],
        ),
    ]
