# Generated by Django 2.1.7 on 2021-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='banners'),
            preserve_default=False,
        ),
    ]
