# Generated by Django 3.2.4 on 2021-07-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210701_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
