# Generated by Django 3.2.4 on 2021-07-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.TextField(max_length=160),
        ),
    ]
