# Generated by Django 3.2.4 on 2021-07-03 08:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=blog.models.get_other_category, on_delete=models.SET(blog.models.get_other_category), to='blog.category'),
        ),
    ]
